name = "Create Ptd 2"
author = "Yarden-zamir"
version = "1.248.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1da32247a44ebb72dde032f36903c4369fe7c36cc45e0cf533289d46c66ab46e"

[versions]
forge = "47.4.13"
minecraft = "1.20.1"
