name = "Create Ptd 2"
author = "Yarden-zamir"
version = "1.236.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "254ed394dae2823c892eefa58cbea0561793d8314ac455aad377a7f63ded9b22"

[versions]
forge = "47.4.13"
minecraft = "1.20.1"
