name = "Create Ptd 2"
author = "Yarden-zamir"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "403c0b8418431a4d3f79c35fb21c0a65a5aa46ece9f7db1c2817dcb8028fefdf"

[versions]
forge = "47.4.13"
minecraft = "1.20.1"
